export const SHOW_ALL_INCIDENTS = 'SHOW_ALL_INCIDENTS';
export const ADD_INCIDENT = 'ADD_INCIDENT';
export const DELETE_INCIDENT = 'DELETE_INCIDENT';
export const UPDATE_INCIDENT = 'UPDATE_INCIDENT';
export const RESOLVE_INCIDENT = 'RESOLVE_INCIDENT';