export const SHOW_ALL_EQUIPMENTS = 'SHOW_ALL_EQUIPMENTS';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const DELETE_EQUIPMENT = 'DELETE_EQUIPMENT';
export const UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT';